### ISSUE TITLE
Suggestion: Retraction tuning wizard

### ISSUE THREAD

**Issue by Chompworks** [jneilliii/OctoPrint-BedLevelingWizard#10]
Apologies for posting this on the BedLevelingWizard project, but it felt like the best place to suggest this as another Wizard that people might appreciate.

So the idea: Ive been thinking personally for a while that an interactive retraction tuning wizard would be good. (sort of like how modern inkjet printers perform nozzle alignment patterns to ensure colours line up correctly). Rather than a manual process of slicing and reslicing with different settings (or at best, trying to do a similar thing via processes in a slicer), and having to keep track of it all, a wizard could automate quite a decent amount of it potentially.

basic idea is:
- wizard is triggered with a desired nozzle and bed temperature 
- wizard prints 5 pairs of separated 10mm cubes (or other suitable models) with varying rough granularity of retraction for pairs (e.g. pair 1 is 0mm retraction, pair 5 is 10mm)
- wizard prompts for choice of best pair (e.g. user picks 3, which in this example would be roughly 6mm retraction)
- wizard then asks user to clear bed, and once cleared wizard then reprints 5 more sets with higher granularity (e.g. based on original round pair 3 looking the best, perhaps 5mm-7mm retraction in 0.5mm steps)
- Again, user picks best, and wizard notes current best settings for the printer. 
-- Potentially continue on down to 0.25mm granularity, or stop at 0.5mm.
- Potentially have a retraction speed tuning (e.g. from 10mm/s up to 90mm/s or similar)
- Potentially update CuraEngine profile to match this new tuned value for users that slice on Pi?

I don't know if the idea's of interest, or if there's better ways to improve finding a good retraction value sooner (maybe the user could even put in a manufacturer value [or last known good value?] to skip step 1?) but looking at the plugins you've made in the past, I figured it might be something you might like the idea of?

**Comment by jneilliii** [comment]
I've posted your idea on the community forum....

https://discourse.octoprint.org/t/plugin-idea-retraction-wizard/3844
