### ISSUE TITLE
Needs more description

### ISSUE THREAD

**Issue by phord** [jneilliii/OctoPrint-BedLevelingWizard#2]
As someone who has no experience with Simplify3D, I do not know what this plugin hopes to do.  Simply saying "it mimics Simplify3D's frobnotz function" is not helpful to me nor others like me.

**Comment by jneilliii** [comment]
Sorry if I'm missing something, but the description on the plugin repo does explain what that function does.  

> This plugin mimcs the Simplify3D Bed Leveling Wizard process. Configure default settings in OctoPrint settings. When ready to level your bed press Start on the plugin’s sidebar panel and adjust that point’s screw. Press Next and then adjust that point’s screw, and repeat until finished.

I can add more information as to what each step does, but I thought based on the description above it would make sense. Maybe something like the following...

> This plugin aids in the manual bed leveling process utilizing a wizard like approach.  Press Start and the printer will lift the nozzle, home all axes and lift the nozzle by the configured Z Travel Height to allow for manual nozzle cleaning, bed heating, etc.  When you are ready to proceed, press Next and the nozzle will be moved to the first point based on the X/Y Axes offset setting and then lower to the configured Z Leveling Height setting. Once at that point adjust the bed screw as necessary to get the desired clearance at that position.  Press Next and the nozzle will lift the configured height again and move to the next leveling position in the diagonally opposite corner.  Adjust the screw at that position until you get the desired clearance and repeat.  The wizard will do 2 cycles of all 4 corners and then you will be presented with a Finish button that when pressed will lift the nozzle a final time and home the X/Y axes.

**Comment by fdamstra** [comment]
Sorry, @jneilliii, but I'm with @phord. The description in the plugin repo is lacking. 

> This plugin mimics the Simplify3D Bed Leveling Wizard process. Configure default settings in OctoPrint settings. When ready to level your bed press Start on the plugin’s sidebar panel and adjust that point’s screw. Press Next and then adjust that point’s screw, and repeat until finished.

The entire paragraph you quoted says absolutely nothing about how to use this plugin. When I'm ready to level I click 'start' and 'adjust the screw'? I can do that without any software. Presumably your plugin does something between those two steps, and it would be helpful to know what that was.

But the rewrite is not better. I'm assuming the goal of this was to make bed leveling easier in some way, but your rewrite basically expects the person to know exactly what they want. 

Does this plugin print squares in the corners of the bed? That might be useful. But from the docs I have no idea if that's actually what it does. From your expanded description, it sounds like it just moves to the corners. Is that it?

**Comment by jneilliii** [comment]
I understand you can do the process yourself.  This was a specific request from the community forum to replicate the wizard in Simplify3D.  More details can be found over [here](https://discourse.octoprint.org/t/manual-bed-leveling-wizard-plugin-suggestion-request/2736). But to summarize, you press start nozzle homes, you press next the nozzle goes to the first corner, you press next, it goes to the diagonally opposite corner, you press next it goes to the third corner, you press next it goes to the diagonally opposite corner. You press next it cycles through all 4 corners again repeating that diagonal pattern waiting for next to be pressed in the wizard.  There is nothing wang-bang special about the plugin, it literally just moves the nozzle around based on offset settings, etc.

**Comment by phord** [comment]
@jneilliii Thanks for that description.  That _is_ far more helpful.  I would add to that a little more description, but it really is 95% of the way there.

* "X/Y Axes offset setting" and "Z Leveling Height setting" -- Are these plugin settings or some expected printer eeprom setting I'm supposed to be aware of?  If they are plugin settings, what are reasonable values to use and why?
* "adjust the bed screw"?  Which bed screw?  The one near the X/Y point, I suppose.  But saying "the" bed screw without prior mention of it is confusing.
* Does the procedure change if I have a three-point bed mount vs. a four-point bed mount?  Should it?

I think I get the gist of it now.  But there are some tools that have "bed leveling wizards" that do involve printing test patterns. It would good to mention that this plugin doesn't print anything, doesn't require any filament, doesn't heat the bed or hot end and does not need them preheated.

**Comment by joeynuggetz** [comment]
Totally agree on the lack of info. Been printing for years and it still had me scratching my head. Especially when we see offsets, what if a crazy value is set could that cause the nozzle to go digging into the users bed? Needs more info.
