### ISSUE TITLE
Feature request -Can you add the ability to expand or hide the panel

### ISSUE THREAD

**Issue by mikeq3** [jneilliii/OctoPrint-BedLevelingWizard#22]
I would like to have the bed leveling wizard hidden when not in use. Like for instance the connect panel does.
Mike

**Comment by jneilliii** [comment]
If you click the title of the sidebar panel it will minimize like the connection panel does.

**Comment by mikeq3** [comment]
I’m sorry I was not clear in my comment. I meant if you could have a plug-in setting that would have it load hidden by default or maybe have it install as part of the controls tab.

**Comment by jneilliii** [comment]
Install the stateful sidebar plugin. https://plugins.octoprint.org/plugins/statefulsidebar/

**Comment by mikeq3** [comment]
That plugin worked great thanks.
