### ISSUE TITLE
Druckbettgröße einstellen?

### ISSUE THREAD

**Issue by Suzi17** [jneilliii/OctoPrint-BedLevelingWizard#36]
Hallo habe das Problem wenn er aus Home den ersten Punkt anfährt dass der Druckkopf zuweit in x und y fahren will. Es scheint so als das die Software für größere Druckbetten gemacht ist . Gibt es die Möglichkeit ,dass ich die Druckbettgröße manuell einzugeben und wenn ja wo? Oder nimmt die Software dass aus konfiguration des Druckers aus Octoprint ?
Und wenn ich es manuell eingeben kann wäre es nett wenn   sie mir was schicken könnten wo ich es einstellen kann?

Danke Mfg Heiko

**Comment by jneilliii** [comment]
The plugin does take the bed size from OctoPrint's printer profile section. If that's not working right, then using the manual probe points might be the best way to go for you. I haven't set this up in a while, so can't really provide a screenshot of how to set that up, but it's in the plugin's settings.
