### ISSUE TITLE
B and C side of printer

### ISSUE THREAD

**Issue by AmmaPysz** [jneilliii/OctoPrint-BedLevelingWizard#43]
Is there a way to change only the B and C side of the printer instead of all. I am looking for a offset to go toward the middle of the bed but only on one side of my printer. I do have a CR touch on my Ender 3 V2 Neo. When I use the wizard my nozzle is at the end of the bed on both the B and C side. A and D are correct and don't need to change those.

**Comment by jneilliii** [comment]
The only way to really handle that is using the custom points instead of the offset options.

**Comment by AmmaPysz** [comment]
Could you please give me an example how I would move it to the left please.

**Comment by jneilliii** [comment]
Something like this would be the equivalent of a 200x200 bed with 10mm offset from all sides.

![image](https://github.com/jneilliii/OctoPrint-BedLevelingWizard/assets/5249455/8baf748a-8d79-407a-b0bd-56643998d480)

**Comment by AmmaPysz** [comment]
Thank you
