### ISSUE TITLE
Startup error with TouchUI enabled, that actually stops touchui-autostart tool

### ISSUE THREAD

**Issue by micdenny** [jneilliii/OctoPrint-BedLevelingWizard#8]
When I enable touchui I get this error in the console:

![image](https://user-images.githubusercontent.com/1633595/43082668-dd781ae6-8e94-11e8-9388-fc5c9ed69bf8.png)

```
Error calling onStartupComplete on view model TouchUI : TypeError: Cannot read property 'show' of undefined
    at HTMLAnchorElement.<anonymous> (http://10.0.112.31/static/webassets/packed_plugins.js?9d717141:2425:64)
    at Function.each (http://10.0.112.31/static/webassets/packed_libs.js?eebed41b:366:19)
    at jQuery.fn.init.each (http://10.0.112.31/static/webassets/packed_libs.js?eebed41b:138:17)
    at TouchUI.DOM.overwrite.tabbar (http://10.0.112.31/static/webassets/packed_plugins.js?9d717141:2422:39)
    at TouchUI.self.onStartupComplete (http://10.0.112.31/static/webassets/packed_plugins.js?9d717141:1620:38)
    at callViewModelIf (http://10.0.112.31/static/webassets/packed_core.js?ccbe5583:13822:34)
    at http://10.0.112.31/static/webassets/packed_core.js?ccbe5583:13768:13
    at Pn (http://10.0.112.31/static/webassets/packed_libs.js?eebed41b:10658:530)
    at Function.<anonymous> (http://10.0.112.31/static/webassets/packed_libs.js?eebed41b:10679:66)
    at callViewModelsIf (http://10.0.112.31/static/webassets/packed_core.js?ccbe5583:13766:7)
```

if I disable this plugin everything works fine touchui-autostart tool work and I don't get any error on the console.

**Comment by micdenny** [comment]
> I'll have to look into that. I'm not exactly sure what touch ui's autostart tool is.

BTW the problem is showing while enabling TouchUI, even in desktop environment.

the autostart tool is this [OctoPrint-TouchUI-autostart](https://github.com/BillyBlaze/OctoPrint-TouchUI-autostart) and it's a tool to [run the touchui on startup of raspberry](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser-(OctoPi-or-Jessie-Light)).

**Comment by jneilliii** [comment]
@outsourcedguru, are you seeing the same thing?

**Comment by OutsourcedGuru** [comment]
I don't think I've seen that. Haven't worked on that rig for a week, though.

**Comment by jneilliii** [comment]
Thanks.  I can definitely see the error on desktop with TouchUI enabled, but it doesn't seem to break functionality within chrome. I'll have to reach out to @BillyBlaze to work this out.

**Comment by micdenny** [comment]
> I can definitely see the error on desktop with TouchUI enabled, but it doesn't seem to break functionality within chrome.

I don't know why it breaks the autostart plugin, if I have time today I also dig into it, but I'm a newbie to octopi development, so don't expect too much 😄

**Comment by micdenny** [comment]
in the meanwhile I downgrade to version `0.1.4` and touchui-autostart boots up just fine

**Comment by micdenny** [comment]
@jneilliii I've did my homeworks 😄 you can check the PR #9 

I don't know if you like what I did, but to me it's much more cleaner to have this feature as a tab, in this way everything works as expected, the icon is set with a small css I've stolen the idea from other plugins and was similar as your but much smaller.

![image](https://user-images.githubusercontent.com/1633595/43150750-fd0c4bd0-8f6a-11e8-8f4c-766b2f0fa63d.png)

![image](https://user-images.githubusercontent.com/1633595/43150734-f577064e-8f6a-11e8-9a7c-0134d37ccea6.png)

If you want to keep a sidebar template for the desktop and tab for touchui, we can do something in the template with a simple if, instead of having one template and try to force it as tab when in touchui mode.

In the meanwhile my fork works fine and the touchui-autostart works perfectly, so I will give it a shot with a real printer (actually I didn't test it with any printer).
